# Generated by Django 3.2.25 on 2024-12-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo001', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
